apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-login-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-login-app
  template:
    metadata:
      labels:
        app: php-login-app
    spec:
      containers:
      - name: php-login-app
        image: my-docker-image:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-login-service
spec:
  selector:
    app: php-login-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-login-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-login-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
